import { DiRedis } from "react-icons/di";
import {
  FaAws,
  FaNodeJs,
  FaPaintBrush,
  FaDocker,
  FaSlack,
} from "react-icons/fa";
import { RiReactjsLine } from "react-icons/ri";
import { MdArchitecture } from "react-icons/md";
import { TbBrandNextjs } from "react-icons/tb";
import {
  SiClerk,
  SiFirebase,
  SiJest,
  SiKubernetes,
  SiMongodb,
  SiOpenai,
  SiPostman,
  SiShadcnui,
  SiSwagger,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiConfluence,
  SiRedux,
} from "react-icons/si";

export const TECH_STACK = [
  {
    name: "React",
    icon: RiReactjsLine,
    color: "text-cyan-400",
    usage: "primary",
    docs: "https://react.dev",
  },
  {
    name: "Next.js",
    icon: TbBrandNextjs,
    color: "text-neutral-100",
    usage: "primary",
    docs: "https://nextjs.org",
  },
  {
    name: "Node.js",
    icon: FaNodeJs,
    color: "text-green-600",
    usage: "backend",
    docs: "https://nodejs.org",
  },
  {
    name: "TypeScript",
    icon: SiTypescript,
    color: "text-blue-400",
    usage: "core",
    docs: "https://typescriptlang.org",
  },
  {
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    color: "text-cyan-400",
    usage: "styling",
    docs: "https://tailwindcss.com",
  },
  {
    name: "Redux Toolkit",
    icon: SiRedux,
    color: "text-purple-500",
    usage: "state",
    docs: "https://redux-toolkit.js.org/",
  },
  {
    name: "MongoDB",
    icon: SiMongodb,
    color: "text-green-500",
    usage: "database",
    docs: "https://mongodb.com",
  },
  {
    name: "Redis",
    icon: DiRedis,
    color: "text-red-500",
    usage: "database",
    docs: "https://redis.io",
  },
  {
    name: "Firebase",
    icon: SiFirebase,
    color: "text-yellow-500",
    usage: "authentication",
    docs: "https://firebase.google.com",
  },
  {
    name: "Swagger",
    icon: SiSwagger,
    color: "text-yellow-400",
    usage: "api",
    docs: "https://swagger.io",
  },
  {
    name: "Postman",
    icon: SiPostman,
    color: "text-orange-500",
    usage: "api",
    docs: "https://postman.com",
  },
  {
    name: "Docker",
    icon: FaDocker,
    color: "text-blue-500",
    usage: "infrastructure",
    docs: "https://www.docker.com/",
  },
  {
    name: "Kubernetes",
    icon: SiKubernetes,
    color: "text-blue-600",
    usage: "infrastructure",
    docs: "https://kubernetes.io",
  },
  {
    name: "CI/CD",
    icon: MdArchitecture,
    color: "text-pink-500",
    usage: "deployment",
    docs: "https://www.atlassian.com/continuous-delivery/ci-vs-cd",
  },
  {
    name: "Vercel",
    icon: SiVercel,
    color: "text-black dark:text-white",
    usage: "deployment",
    docs: "https://vercel.com",
  },
  {
    name: "AWS",
    icon: FaAws,
    color: "text-amber-600",
    usage: "cloud",
    docs: "https://aws.amazon.com",
  },
  {
    name: "Clerk",
    icon: SiClerk,
    color: "text-purple-500/80",
    usage: "authentication",
    docs: "https://clerk.dev",
  },
  {
    name: "shadcn/ui",
    icon: SiShadcnui,
    color: "text-sky-400",
    usage: "components",
    docs: "https://ui.shadcn.com",
  },
  {
    name: "Jest",
    icon: SiJest,
    color: "text-red-500",
    usage: "testing",
    docs: "https://jestjs.io",
  },
  {
    name: "Confluence",
    icon: SiConfluence,
    color: "text-blue-400",
    usage: "documentation",
    docs: "https://www.atlassian.com/software/confluence",
  },
  {
    name: "Slack",
    icon: FaSlack,
    color: "text-purple-400",
    usage: "communication",
    docs: "https://slack.com",
  },
  {
    name: "ChatGPT",
    icon: SiOpenai,
    color: "text-green-400/80",
    usage: "ai",
    docs: "https://openai.com/chatgpt",
  },
];
